<c:url var="url" value="/resources/" />

    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="${url}js/bootstrap-transition.js"></script>
    <script src="${url}js/bootstrap-alert.js"></script>
    <script src="${url}js/bootstrap-modal.js"></script>
    <script src="${url}js/bootstrap-dropdown.js"></script>
    <script src="${url}js/bootstrap-scrollspy.js"></script>
    <script src="${url}js/bootstrap-tab.js"></script>
    <script src="${url}js/bootstrap-tooltip.js"></script>
    <script src="${url}js/bootstrap-popover.js"></script>
    <script src="${url}js/bootstrap-button.js"></script>
    <script src="${url}js/bootstrap-collapse.js"></script>
    <script src="${url}js/bootstrap-carousel.js"></script>
    <script src="${url}js/bootstrap-typeahead.js"></script>

  </body>
</html>